datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ekaterinaefimova
    password: password
    url: "jdbc:postgresql:postgres"

ebean:
  migration:
    run: true